api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('info/', views.asterisk_info, name='info'),
    path('variable/', views.asterisk_variable, name='variable'),
    path('bridges/', views.bridges, name='bridges'),
    path('channels/', views.channels, name='channels'),
    path('states/', views.device_states, name='states'),
    path('endpoints/', views.endpoints, name='endpoints'),
    path('events/', views.events, name='events'),
    path('mailboxes/', views.mailboxes, name='mailboxes'),
    path('stored/', views.recordings_stored, name='stored'),
    path('sounds/', views.sounds, name='sounds'),
]

asterisk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome_view, name='welcome'),
]

api/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Server(models.Model):
    name = models.CharField(max_length=200)
    ip = models.GenericIPAddressField()
    port = models.IntegerField()
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    content = models.TextField()

    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.ip}:{self.port}"


class Costumer(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.user} : {self.server}"

subscriber/models.py
from django.db import models


class Subscriber(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    number = models.IntegerField(verbose_name="Number")
    tech = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.number}"


class Control(models.Model):
    subscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
    online = models.DateTimeField(verbose_name="Online", auto_now_add=True)
    offline = models.DateTimeField(null=True, blank=True, verbose_name="Offline")

    def __str__(self):
        return f"{self.subscriber} - {self.online}"

api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from . import function


@api_view()
def welcome(request):
    data = function.get_applications()
    return Response(data)


@api_view()
def asterisk_info(request):
    info = function.get_asterisk_info()
    ping = function.get_asterisk_ping()
    modules = function.get_asterisk_modules()
    logging = function.get_asterisk_logging()
    data = {
        'info': info,
        'ping': ping,
        'modules': modules,
        'logging': logging
    }
    return Response(data)


@api_view()
def asterisk_variable(request):
    data = function.get_asterisk_variable()
    return Response(data)


@api_view()
def bridges(request):
    data = function.get_bridges()
    return Response(data)


@api_view()
def channels(request):
    data = function.get_channels()
    return Response(data)


@api_view()
def device_states(request):
    data = function.get_deviceStates()
    return Response(data)


@api_view()
def endpoints(request):
    data = function.get_endpoints()
    return Response(data)


@api_view()
def events(request):
    data = function.get_events()
    return Response(data)


@api_view()
def mailboxes(request):
    data = function.get_mailboxes()
    return Response(data)


@api_view()
def recordings_stored(request):
    data = function.get_recordings_stored()
    return Response(data)


@api_view()
def sounds(request):
    data = function.get_sounds()
    return Response(data)

asterisk/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_view(request):
    if request.user.is_authenticated:
        return redirect('main:welcome')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.add_message(request, messages.SUCCESS, f"{username} siz tizimga muvafaqqiyatli kirdingiz :)")
                return redirect('main:welcome')
    return render(request, 'auth/login.html')


def logout_view(request):
    logout(request)
    return redirect('login')

main/views.py
from django.shortcuts import render
from .models import Server, Costumer
from django.contrib.auth.decorators import login_required
from .functions import get_server


@login_required(login_url='login')
def welcome_view(request):
    user = request.user
    costumers = Costumer.objects.filter(user=user)
    try:
        servers = get_server(costumers)
    except Exception as e:
        pass
    print(servers)
    context = {
        'costumers': costumers,
        'servers': servers
    }
    return render(request, 'main/welcome.html', context)


def index(request):
    print(request.user)
    return render(request, 'main/index.html')

subscriber/views.py
from django.shortcuts import render

# Create your views here.

templates/main/index.html
{% extends 'base.html' %}
{% block title %}
	Welcome -
{% endblock %}
{% block content %}

<h1>Asterisk all data check everywhere</h1>
<p><a href="{% url 'api:welcome' %}">Welcome</a></p>
<p><a href="{% url 'api:info' %}">Info</a></p>
<p><a href="{% url 'api:variable' %}">Variable</a></p>
<p><a href="{% url 'api:bridges' %}">Bridges</a></p>
<p><a href="{% url 'api:channels' %}">Channels</a></p>
<p><a href="{% url 'api:states' %}">States</a></p>
<p><a href="{% url 'api:endpoints' %}">Endpoints</a></p>
<p><a href="{% url 'api:events' %}">Events</a></p>
<p><a href="{% url 'api:mailboxes' %}">Mailbox</a></p>
<p><a href="{% url 'api:stored' %}">Stored</a></p>
<p><a href="{% url 'api:sounds' %}">Sounds</a></p>


{% endblock %}

templates/main/welcome.html
{% extends 'base.html' %}

{% block content %}

    {% for server in servers %}
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title text-success">{{ server.ip }}</strong>

                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Abonent</th>
                            <th scope="col">Status</th>
                            <th scope="col">Tech</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for endpoint in server.endpoints %}
                            <tr>
                                <th scope="col">{{ forloop.counter }}</th>
                                <th scope="col">{{ endpoint.abonent }}</th>
                                <th scope="col">{{ endpoint.status }}</th>
                                <th scope="col">{{ endpoint.technology }}</th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endfor %}


{% endblock %}